id: aphp.fhir.fr.dm
canonical: https://aphp.fr/ig/fhir/dm
name: DM
title: Data Management with FHIR
description: "Ce guide d'implémentation décrit: (i) le processus d'alimentation d'un hub de données de santé, (ii) les cas d'usages traités et, in fine, (iii) la liste des données présentes dans le hub de données de santé d'un SIH."
status: draft
version: 0.1.0
jurisdiction: urn:iso:std:iso:3166#FR "France"
fhirVersion: 4.0.1
copyrightYear: 2023+
releaseLabel: ci-build
# license: CC0-1.0 # https://www.hl7.org/fhir/valueset-spdx-license.html
publisher:
  name: AP-HP
  url: https://aphp.fr
  # email: test@example.org

dependencies:
  hl7.fhir.uv.sdc: 3.0.0
  hl7.fhir.fr.core: 2.1.0
  ans.fhir.fr.annuaire: 1.1.0

pages:
  index.md:
    title: Accueil
  data-dictionary.md:
    title: Dictionnaire des données
  use-case.md:
    title: Usages
    use-core.md:
      title: Variables socles
  data-management.md:
    title: Gestion des données
  best-practice.md:
    title: Bonnes pratiques
  other.md:
    title: Autre
    help.md:
      title: Aide
    change_log.md:
      title: Notes de version
    glossary.md:
      title: Glossaire
    downloads.md:
      title: Télécharger les spécifications

menu:
  Accueil: index.html
  Dictionnaire des données: data-dictionary.html
  Usages:
    Variables socles: use-core.html
  Gestion des données: data-management.html
  Bonnes pratiques: best-practice.html
  Ressources de conformité: artifacts.html
  Autres:
    Aide: help.html
    Notes de version: change_log.html
    Glossaire: glossary.html
    Télécharger spécifications: downloads.html

parameters:  # see https://build.fhir.org/ig/FHIR/fhir-tools-ig/CodeSystem-ig-parameters.html
  shownav: false
  pin-canonicals: pin-multiples # Avoid raising many warnings when there are no version for URLs. "pin-multiples": pinning the canonical reference will only happen if there is multiple versions found in the package dependencies
  path-expansion-params: 
    - ../../input/data/expansion-params.json # for using French SNOMED CT Extension
  path-resource:
    - input/resources/usages/core
    - input/fml/usages/core
    - input/test-map/usages/core

# The instanceOptions property is used to configure certain aspects of how SUSHI processes instances.
instanceOptions:
  setMetaProfile: always # Determines for which types of Instances SUSHI will automatically set meta.profile if InstanceOf references a profile
  setId: always # Determines for which types of Instances SUSHI will automatically set id if InstanceOf references a profile

#  logging:
#    - tx #tx: Messages describing the use of the terminology server (for debugging)
#    - html #html: Log when validating a html page (troubleshooting only - leave off)
#    - generate #generate: Log when producing an individual resource (troubleshooting only - leave off)
#    - init #init: Messages describing the start up process (for debugging)
#    - progress #progress: Overall progress messages
