id: aphp.fhir.fr.dm
canonical: https://interop.aphp.fr/ig/fhir/dm
name: DM
title: Data Management with FHIR
description: "Ce guide d'implémentation décrit: (i) le processus d'alimentation d'un hub de données de santé, (ii) les cas d'usages traités et, in fine, (iii) la liste des données présentes dans le hub de données de santé d'un SIH."
status: draft
version: 0.1.0
jurisdiction: urn:iso:std:iso:3166#FR "France"
fhirVersion: 4.0.1
copyrightYear: 2023+
releaseLabel: ci-build
# license: CC0-1.0 # https://www.hl7.org/fhir/valueset-spdx-license.html
publisher:
  name: AP-HP
  url: https://aphp.fr
  # email: test@example.org

dependencies:
  hl7.fhir.uv.sdc: 3.0.0
  hl7.fhir.fr.core: 2.1.0
  ans.fhir.fr.annuaire: 1.1.0
  #org.sql-on-fhir.ig:
  #  uri: https://sql-on-fhir.org/ig
  #  version: 2.0.0

pages:
  index.md:
    title: Accueil
  use-case.md:
    title: Usages
    use-core-variables.md:
      title: Variables socles pour les EDSH
      use-core-variables-process.md:
        title: Standardisation de données au format FHIR
        use-core-variables-acquisition.md:
          title: Acquisition de la liste des variables
        use-core-variables-formalization.md:
          title: Formalisation des variables
        use-core-variables-standardization.md:
          title: Standardisation des variables
      use-core-variables-evaluation.md:
        title: Evaluation
  data-platform.md:
    title: Health Data Platform (démo)
    data-platform-raw-layer.md:
      title: Raw layer
    data-platform-transform-layer.md:
      title: Transform layer
    data-platform-semantic-layer.md:
      title: Semantic layer
    data-platform-share-layer.md:
      title: Share layer
  other.md:
    title: Autre
    help.md:
      title: Aide
    change_log.md:
      title: Notes de version
    glossary.md:
      title: Glossaire
    downloads.md:
      title: Télécharger les spécifications

menu:
  Accueil: index.html
  Recommandation:
    Gestion des données: new-tab https://interop.aphp.fr/ig/fhir/core/data-management.html
    Bonnes pratiques: new-tab https://interop.aphp.fr/ig/fhir/core/best-practice.html
    Processus de standardisation des données: https://interop.aphp.fr/ig/fhir/core/standardization-process.html
  Variables du socle: use-core-variables.html
  Health Data Platform: data-platform.html
  Ressources de conformité: artifacts.html
  Autres:
    Aide: help.html
    Notes de version: change_log.html
    Glossaire: glossary.html
    Télécharger spécifications: downloads.html

parameters:  # see https://build.fhir.org/ig/FHIR/fhir-tools-ig/CodeSystem-ig-parameters.html
  shownav: false
  pin-canonicals: pin-multiples # Avoid raising many warnings when there are no version for URLs. "pin-multiples": pinning the canonical reference will only happen if there is multiple versions found in the package dependencies
  path-expansion-params: '../../input/data/expansion-params.json' # for using French SNOMED CT Extension
  path-resource:
    - input/resources/usages/core
    - input/fml
    - input/fml/usages/core

# The instanceOptions property is used to configure certain aspects of how SUSHI processes instances.
instanceOptions:
  setMetaProfile: always # Determines for which types of Instances SUSHI will automatically set meta.profile if InstanceOf references a profile
  setId: always # Determines for which types of Instances SUSHI will automatically set id if InstanceOf references a profile

#  logging:
#    - tx #tx: Messages describing the use of the terminology server (for debugging)
#    - html #html: Log when validating a html page (troubleshooting only - leave off)
#    - generate #generate: Log when producing an individual resource (troubleshooting only - leave off)
#    - init #init: Messages describing the start up process (for debugging)
#    - progress #progress: Overall progress messages

resources:
  Questionnaire/UsageCore:
    name: Questionnaire usage Variables socles pour les EDSH
    description: Formalisation de variables socles pour les EDSH
    exampleBoolean: false
  QuestionnaireResponse/test-usage-core:
    name: Exemple simple
    description: Exemple simple
    exampleBoolean: true
  QuestionnaireResponse/test-usage-core-complet:
    name: Exemple complet
    description: Exemple complet
    exampleBoolean: true
  QuestionnaireResponse/test-usage-core-patient-9:
    name: Patient 9 - Madame Blanc
    description: Exemple correspondant au patient 9 du jeu de test
    exampleBoolean: true
  Bundle/5616f9ad-61b0-4279-9f41-777228d04665:
    name: Patient test (Bundle)
    description: ???
    exampleBoolean: true
  Bundle/2abf7f4c-bd1f-431f-a4c8-667cfa425baf:
    name: Test simple
    description: ???
    exampleBoolean: true
  Patient/8f005d60-b59b-47f7-b04a-f877378f8d68:
    name: Patient test (Ressource)
    description: ???
    exampleBoolean: true
  Bundle/df9c9a9c-854b-46f4-9687-1fbe40c06540:
    name: Exemple complet (FSL)
    description: Exemple de réponse au questionnaire au format FHIR
    exampleBoolean: true