# Simplified EHR to FHIR Semantic Layer Transformation Project

name: 'ehr_fhir_transform'
version: '1.0.0'
config-version: 2

profile: 'transform_layer'

# Model paths
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

# Variables (simplified)
vars:
  # Source database schema
  ehr_schema: 'public'
  
  # Target FHIR schema
  fhir_schema: 'fhir_semantic_layer'
  
  # Timezone for timestamp conversions
  timezone: 'Europe/Paris'
  
  # FHIR version
  fhir_version: '4.0.1'
  
  # Incremental strategy
  incremental_lookback_days: 7

# Model configuration (simplified)
models:
  ehr_fhir_transform:
    # Staging layer
    staging:
      +materialized: view
      +tags: ["staging"]
      
    # Intermediate layer
    intermediate:
      +materialized: view
      +tags: ["intermediate"]
      
    # Marts layer
    marts:
      +materialized: table
      +tags: ["mart", "fhir"]

# Seeds configuration
seeds:
  ehr_fhir_transform:
    +quote_columns: false
    ehr_test_patient:
      +column_types:
        patient_id: bigint
        nom: varchar(255)
        prenom: varchar(255)
        nir: varchar(15)
        ins: varchar(50)
        date_naissance: date
        sexe: varchar(20)
        date_deces: date
        source_deces: varchar(50)
        rang_gemellaire: integer
        latitude: decimal(10,7)
        longitude: decimal(10,7)
        code_iris: varchar(20)
        libelle_iris: varchar(200)
        code_geographique_residence: varchar(10)
        libelle_geographique_residence: varchar(200)
        created_at: timestamp
        updated_at: timestamp

# Tests configuration
tests:
  ehr_fhir_transform:
    +store_failures: true
    +severity: warn