# Multi-database configuration example
# Copy to ~/.dbt/profiles.yml

ehr_fhir_transform:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DBT_HOST', 'localhost') }}"
      port: "{{ env_var('DBT_PORT', 5432) | int }}"
      user: "{{ env_var('DBT_USER') }}"
      pass: "{{ env_var('DBT_PASSWORD') }}"
      
      # Default target database for transformations and final output
      dbname: "{{ env_var('DBT_DATABASE', 'theRing') }}"
      schema: "{{ env_var('DBT_SCHEMA', 'public') }}"
      threads: 4
      keepalives_idle: 0
      sslmode: prefer
