# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'ehr_to_fhir_semantic_layer'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'ehr_transform_layer'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/reference/model-configs
models:
  ehr_to_fhir_semantic_layer:
    # Config indicated by + and applies to all files under models/staging/
    staging:
      +materialized: view
      +schema: staging
    # Config indicated by + and applies to all files under models/intermediate/
    intermediate:
      +materialized: view
      +schema: intermediate
    # Config indicated by + and applies to all files under models/marts/
    marts:
      +materialized: table
      +schema: fhir_semantic_layer
      # Specific configurations for FHIR resource tables
      fhir:
        +materialized: table
        +indexes:
          - columns: ['id']
            unique: true
        +post-hook: "ANALYZE {{ this }}"
      #monitoring:
      #  +materialized: table
      #  +tags: ['monitoring']

# Seeds configuration
seeds:
  ehr_to_fhir_semantic_layer:
    +schema: seeds
    +quote_columns: false
    # Specify column types for seeds to ensure proper data types
    patient:
      +column_types:
        patient_id: "bigint"
        nir: "varchar(15)"
        ins: "varchar(15)" 
        date_naissance: "date"
        date_deces: "date"
        rang_gemellaire: "integer"
    donnees_pmsi:
      +column_types:
        pmsi_id: "bigint"
        patient_id: "bigint"
        date_debut_sejour: "date"
        date_fin_sejour: "date"
        age_admission: "integer"
    biologie:
      +column_types:
        biologie_id: "bigint"
        patient_id: "bigint"
        code_loinc: "varchar(20)"
        valeur: "decimal(15,6)"
        borne_inf_normale: "decimal(15,6)"
        borne_sup_normale: "decimal(15,6)"
        date_prelevement: "timestamp with time zone"
    prescription:
      +column_types:
        prescription_id: "bigint"
        patient_id: "bigint"
        code_atc: "varchar(20)"
        date_prescription: "date"
        date_debut_prescription: "date" 
        date_fin_prescription: "date"
    posologie:
      +column_types:
        posologie_id: "bigint"
        prescription_id: "bigint"
        quantite: "decimal(10,3)"
        nombre_prises_par_jour: "integer"
        date_heure_debut: "timestamp"
        date_heure_fin: "timestamp"
    administration:
      +column_types:
        administration_id: "bigint"
        patient_id: "bigint"
        prescription_id: "bigint"
        quantite: "decimal(10,3)"
        code_atc: "varchar(20)"
        date_heure_debut: "timestamp"
        date_heure_fin: "timestamp"
    diagnostics:
      +column_types:
        diagnostic_id: "bigint"
        patient_id: "bigint"
        pmsi_id: "bigint"
        code_diagnostic: "varchar(20)"
        date_recueil: "date"
    actes:
      +column_types:
        acte_id: "bigint"
        patient_id: "bigint"
        pmsi_id: "bigint"
        code_acte: "varchar(20)"
        date_acte: "timestamp"
        date_recueil: "date"
    dossier_soins:
      +column_types:
        soin_id: "bigint"
        patient_id: "bigint"
        code_loinc: "varchar(20)"
        valeur: "decimal(15,6)"
        date_mesure: "date"
    style_vie:
      +column_types:
        style_vie_id: "bigint"
        patient_id: "bigint"
        date_recueil: "date"
    patient_adresse:
      +column_types:
        patient_adresse_id: "bigint"
        patient_id: "bigint"
        latitude: "decimal(10,7)"
        longitude: "decimal(10,7)"
        code_iris: "varchar(20)"
        libelle_iris: "varchar(200)"
        code_geographique_residence: "varchar(10)"
        libelle_geographique_residence: "varchar(100)"
        date_recueil: "date"

# Vars - variables that can be referenced in models
vars:
  # Source database connection settings
  source_database: "ehr"
  target_database: "transform_layer"
  
  # Date range for incremental processing
  start_date: '2020-01-01'
  end_date: '2024-12-31'
  
  # FHIR configuration
  fhir_base_url: "https://interop.aphp.fr/ig/fhir/dm"
  fhir_version: "4.0.1"

# Tests configuration
tests:
  +store_failures: true
  +schema: dbt_test_results

# Dispatch configuration for macro overrides
dispatch:
  - macro_namespace: dbt_utils
    search_order: ['ehr_to_fhir_semantic_layer', 'dbt_utils']