# PostgreSQL profile for EHR to FHIR Semantic Layer transformation
ehr_transform_layer:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: postgres
      password: "{{ env_var('DBT_POSTGRES_PASSWORD', 'postgres') }}"
      port: 5432
      dbname: transform_layer
      schema: dbt_dev
      threads: 4
      keepalives_idle: 0 # default 0, indicating the system default
      search_path: "public,dbt_staging,dbt_intermediate,dbt_fhir_semantic_layer,dbt_seeds"
    
    prod:
      type: postgres
      host: localhost
      user: postgres
      password: "{{ env_var('DBT_POSTGRES_PASSWORD', 'postgres') }}"
      port: 5432
      dbname: transform_layer
      schema: dbt_prod
      threads: 8
      keepalives_idle: 0
      search_path: "public,dbt_staging,dbt_intermediate,dbt_fhir_semantic_layer,dbt_seeds"

    test:
      type: postgres
      host: localhost
      user: postgres
      password: "{{ env_var('DBT_POSTGRES_PASSWORD', 'postgres') }}"
      port: 5432
      dbname: transform_layer
      schema: dbt_test
      threads: 2
      keepalives_idle: 0
      search_path: "public,dbt_staging,dbt_intermediate,dbt_fhir_semantic_layer,dbt_seeds"